######################################################################
# Automatically generated by qmake (2.01a) mer. 25. juin 17:13:47 2008
######################################################################

CONFIG += release
QT += network
QT += widgets

# Input
HEADERS += Client.h
FORMS += Client.ui
SOURCES += Client.cpp mainclient.cpp
