######################################################################
# Automatically generated by qmake (2.01a) mer. 25. juin 14:54:55 2008
######################################################################

CONFIG += release
QT += network
QT += widgets

# Input
HEADERS += server.h
SOURCES += server.cpp mainserveur.cpp
