######################################################################
# Automatically generated by qmake (2.01a) mer. 25. juin 17:13:47 2008
######################################################################

CONFIG += release
QT += network
QT += widgets

# Input
HEADERS += client.h #../interfaces/player.h
FORMS += Client.ui
SOURCES += client.cpp mainclient.cpp #../interfaces/player.cpp
